export const memoryStore = {
  users: [
    {
      _id: 'user_admin_theprojectxia',
      name: 'ProjectXia Super Admin',
      email: 'theprojectxia@gmail.com',
      mobile: '+91 99999 00001',
      role: 'owner',
      avatar: 'https://images.unsplash.com/photo-1560250097-0b93528c311a?w=200&auto=format&fit=crop&q=80',
      bio: 'ProjectXia Official Platform Owner & Command Administrator. Overseeing all platform logins, agency development requests, and security audits.',
      skills: ['Zero-Trust Security', 'Full-Stack Architecture', 'System Auditing', 'Go', 'Kubernetes'],
      education: 'M.Tech in Cyber Security & Software Systems',
      experience: 'Platform Security Director',
      github: 'https://github.com/theprojectxia',
      linkedin: 'https://linkedin.com/company/projectxia',
      portfolio: 'https://projectxia.io',
      isVerified: true,
      verificationLevel: 'Tier 3 - Master Architect',
      isBanned: false,
      reputationScore: 100,
      savedProjects: [],
      purchasedProjects: [],
    },
    {
      _id: 'user_001_buyer',
      name: 'Georgekutty Puthusseril',
      email: 'theprojectxia@gmail.com',
      mobile: '+91 99999 11111',
      role: 'user',
      avatar: 'https://images.unsplash.com/photo-1535713875002-d1d0cf377fde?w=200&auto=format&fit=crop&q=80',
      bio: 'Platform Innovator & Client',
      skills: ['React', 'Node.js', 'System Architecture'],
      education: 'B.Tech / Computer Science',
      experience: 'Software Engineer',
      github: 'https://github.com/christopajeesh',
      linkedin: 'https://linkedin.com',
      portfolio: 'https://projectxia.com',
      isVerified: true,
      verificationLevel: 'Verified User',
      isBanned: false,
      reputationScore: 100,
      savedProjects: [],
      purchasedProjects: [],
    },
    {
      _id: 'user_002_creator',
      name: 'Dr. Priya Venkatesh',
      email: 'priya.creator@projectxia.io',
      mobile: '+91 94451 88720',
      role: 'creator',
      avatar: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=200&auto=format&fit=crop&q=80',
      bio: 'Lead AI Researcher & Cybersecurity Architect. Author of 6 IEEE papers on Neural Network defense & Embedded Systems.',
      skills: ['PyTorch', 'TensorRT', 'Cybersecurity', 'Rust', 'ESP32', 'FreeRTOS'],
      education: 'Ph.D in AI Security / IISc Bangalore',
      experience: 'Senior Research Scientist & Engineering Faculty',
      github: 'https://github.com/priya-venkat-ai',
      linkedin: 'https://linkedin.com/in/dr-priya-venkatesh',
      portfolio: 'https://priyavenkat.tech',
      isVerified: true,
      verificationLevel: 'Tier 3 - Master Architect',
      isBanned: false,
      reputationScore: 99,
      savedProjects: [],
      purchasedProjects: [],
    },
  ],

  agencyLeads: [
    {
      _id: 'lead_001',
      name: 'Vikas Deshmukh',
      email: 'vikas.deshmukh@vit.ac.in',
      mobile: '+91 98450 11234',
      dept: 'Electronics & Comm (ECE)',
      projectType: 'IoT / Embedded Hardware + Software',
      budget: '₹12,000 - ₹20,000',
      description: 'Need a customized Smart Water Distribution Network with LoRa 868MHz and ultrasonic level sensors for our municipal capstone submission.',
      emailCopyStatus: 'DISPATCHED_TO_THEPROJECTXIA@GMAIL.COM',
      dispatchedAt: new Date(Date.now() - 1000 * 60 * 45),
      createdAt: new Date(Date.now() - 1000 * 60 * 45),
      status: 'PENDING_REVIEW',
    },
    {
      _id: 'lead_002',
      name: 'Ananya Roy',
      email: 'ananya.roy@startuplabs.in',
      mobile: '+91 97112 33456',
      dept: 'Computer Science (CSE / IT)',
      projectType: 'Full-Stack Web / Mobile App',
      budget: '₹25,000 - ₹50,000',
      description: 'Looking to build an autonomous multi-tenant telemedicine and appointment booking portal with WebRTC video calling.',
      emailCopyStatus: 'DISPATCHED_TO_THEPROJECTXIA@GMAIL.COM',
      dispatchedAt: new Date(Date.now() - 1000 * 60 * 120),
      createdAt: new Date(Date.now() - 1000 * 60 * 120),
      status: 'QUOTE_SENT',
    },
  ],

  projects: [
    {
      _id: 'proj_001_retina_ai',
      title: 'DiabeticRetina-AI: Deep CNN for Retinopathy Detection',
      tagline: 'PyTorch ResNet-50 & Grad-CAM visual heatmaps for fundus image classification.',
      description: 'Production-ready ResNet-50 & EfficientNet-B4 PyTorch model for automated diabetic retinopathy classification from fundus photography. Includes Kaggle dataset scripts and Grad-CAM interpretability.',
      category: 'AI & Data Science (AI / ML)',
      price: 3499,
      projectType: 'Software Only',
      seller: {
        id: 'user_002_creator',
        name: 'Dr. Priya Venkatesh',
        email: 'priya.creator@projectxia.io',
        avatar: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=150&auto=format&fit=crop&q=80',
      },
      screenshots: [
        'https://images.unsplash.com/photo-1576091160399-112ba8d25d1d?w=800&auto=format&fit=crop&q=80',
      ],
      techStack: ['PyTorch', 'Grad-CAM', 'Python', 'Flask'],
      tags: ['AI', 'Medical Vision', 'Deep Learning', 'PyTorch'],
      demoVideoUrl: 'https://www.youtube.com/embed/dQw4w9WgXcQ',
      githubUrl: 'https://github.com',
      isVerified: true,
      trustScore: 98,
      createdAt: new Date(),
    },
    {
      _id: 'proj_002_smartagri_lora',
      title: 'LoRaAgri: ESP32 LoRaWAN Long-Range Smart Irrigation',
      tagline: 'Sub-GHz 868MHz mesh sensor node with solar charging & KiCad PCB.',
      description: 'Long-range sub-GHz soil moisture & solar weather station node using ESP32, SX1276 LoRa, and KiCad PCB schematics. Tested in agricultural fields.',
      category: 'Electronics & Comm (ECE)',
      price: 4999,
      projectType: 'Hardware + Software',
      seller: {
        id: 'user_002_creator',
        name: 'Dr. Priya Venkatesh',
        email: 'priya.creator@projectxia.io',
        avatar: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=150&auto=format&fit=crop&q=80',
      },
      screenshots: [
        'https://images.unsplash.com/photo-1518770660439-4636190af475?w=800&auto=format&fit=crop&q=80',
      ],
      techStack: ['ESP32', 'LoRaWAN', 'FreeRTOS', 'KiCad PCB'],
      tags: ['IoT', 'LoRa', 'Embedded', 'ECE'],
      demoVideoUrl: 'https://www.youtube.com/embed/dQw4w9WgXcQ',
      githubUrl: 'https://github.com',
      isVerified: true,
      trustScore: 96,
      createdAt: new Date(),
    },
    {
      _id: 'proj_003_neuromesh',
      title: 'NeuroMesh AI: Autonomous Edge Vision & Object Tracker',
      tagline: 'TensorRT C++ 120 FPS object detector optimized for Jetson Nano.',
      description: 'TensorRT C++ accelerated Real-Time YOLOv8 object detector for Jetson Nano with OpenCV live video pipeline. Features sub-10ms inference latency.',
      category: 'Computer Science (CSE / IT)',
      price: 5999,
      projectType: 'Software Only',
      seller: {
        id: 'user_002_creator',
        name: 'Dr. Priya Venkatesh',
        email: 'priya.creator@projectxia.io',
        avatar: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=150&auto=format&fit=crop&q=80',
      },
      screenshots: [
        'https://images.unsplash.com/photo-1526374965328-7f61d4dc18c5?w=800&auto=format&fit=crop&q=80',
      ],
      techStack: ['C++', 'TensorRT', 'YOLOv8', 'OpenCV'],
      tags: ['Edge AI', 'Computer Vision', 'Jetson', 'C++'],
      demoVideoUrl: 'https://www.youtube.com/embed/dQw4w9WgXcQ',
      githubUrl: 'https://github.com',
      isVerified: true,
      trustScore: 99,
      createdAt: new Date(),
    },
    {
      _id: 'proj_004_bms_battery',
      title: 'SmartBMS: Active Cell Balancing Electric Vehicle BMS',
      tagline: 'STM32 Lithium BMS with CAN-Bus telemetry and active cell balancing.',
      description: 'STM32F4-based Lithium Battery Management System with CAN-Bus telemetry, active flying-capacitor cell balancing, and OLED display.',
      category: 'Electrical Engineering (EEE)',
      price: 6499,
      projectType: 'Hardware + Software',
      seller: {
        id: 'user_002_creator',
        name: 'Dr. Priya Venkatesh',
        email: 'priya.creator@projectxia.io',
        avatar: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=150&auto=format&fit=crop&q=80',
      },
      screenshots: [
        'https://images.unsplash.com/photo-1558441719-aa34ff501f21?w=800&auto=format&fit=crop&q=80',
      ],
      techStack: ['STM32', 'CAN-Bus', 'KiCad', 'Embedded C'],
      tags: ['EV', 'BMS', 'Battery', 'EEE'],
      demoVideoUrl: 'https://www.youtube.com/embed/dQw4w9WgXcQ',
      githubUrl: 'https://github.com',
      isVerified: true,
      trustScore: 97,
      createdAt: new Date(),
    },
  ],

  conversations: [],

  messages: [],

  notifications: [
    {
      _id: 'notif_001',
      userId: 'user_001_buyer',
      title: 'Shield Security Verification Passed',
      message: 'Your identity was authenticated with 100% genuine clearance.',
      type: 'security_shield',
      actionUrl: '/profile',
      isRead: false,
      createdAt: new Date(Date.now() - 1000 * 60 * 30),
    },
  ],

  auditLogs: [
    {
      _id: 'log_001',
      action: 'USER_LOGGED_IN',
      category: 'AUTH_AUDIT',
      performedBy: {
        id: 'user_001_buyer',
        name: 'Rohan Sharma',
        email: 'rohan.buyer@projectxia.io',
        role: 'user',
      },
      targetEntity: {
        entityType: 'SESSION',
        entityId: 'sess_99182',
        title: 'User Login Authentication',
      },
      ipAddress: '122.164.82.11 (Airtel Broadband, Mumbai)',
      threatLevel: 'CLEAN',
      details: {
        device: 'Chrome / Windows 11 (Secure Node)',
        dispatchedEmail: 'theprojectxia@gmail.com',
        timestamp: new Date(Date.now() - 1000 * 60 * 8),
      },
      createdAt: new Date(Date.now() - 1000 * 60 * 8),
    },
    {
      _id: 'log_002',
      action: 'AGENCY_DEV_REQUEST_SUBMITTED',
      category: 'AGENCY_PIPELINE',
      performedBy: {
        id: 'lead_001',
        name: 'Vikas Deshmukh',
        email: 'vikas.deshmukh@vit.ac.in',
        role: 'client',
      },
      targetEntity: {
        entityType: 'AGENCY_LEAD',
        entityId: 'lead_001',
        title: 'IoT / LoRa Smart Water Project',
      },
      ipAddress: '115.112.45.90 (Pune, Maharashtra)',
      threatLevel: 'INFO',
      details: {
        budget: '₹12,000 - ₹20,000',
        dispatchedTo: 'theprojectxia@gmail.com',
        timestamp: new Date(Date.now() - 1000 * 60 * 45),
      },
      createdAt: new Date(Date.now() - 1000 * 60 * 45),
    },
  ],
};
