export const memoryStore = {
  users: [
    {
      _id: 'user_admin_theprojectxia',
      name: 'ProjectXia Super Admin',
      email: 'theprojectxia@gmail.com',
      mobile: '+91 99999 00001',
      role: 'owner',
      avatar: 'https://images.unsplash.com/photo-1560250097-0b93528c311a?w=200&auto=format&fit=crop&q=80',
      bio: 'ProjectXia Official Platform Owner & Command Administrator. Overseeing all platform logins, agency development requests, and security audits.',
      skills: ['Zero-Trust Security', 'Full-Stack Architecture', 'System Auditing', 'Go', 'Kubernetes'],
      education: 'M.Tech in Cyber Security & Software Systems',
      experience: 'Platform Security Director',
      github: 'https://github.com/theprojectxia',
      linkedin: 'https://linkedin.com/company/projectxia',
      portfolio: 'https://projectxia.io',
      isVerified: true,
      verificationLevel: 'Tier 3 - Master Architect',
      isBanned: false,
      reputationScore: 100,
      savedProjects: [],
      purchasedProjects: [],
    },
    {
      _id: 'user_001_buyer',
      name: 'Rohan Sharma',
      email: 'rohan.buyer@projectxia.io',
      mobile: '+91 98201 55432',
      role: 'user',
      avatar: 'https://images.unsplash.com/photo-1535713875002-d1d0cf377fde?w=200&auto=format&fit=crop&q=80',
      bio: 'Engineering Student & Tech Founder sourcing verified capstone and production code.',
      skills: ['React', 'Python', 'IoT', 'Embedded C'],
      education: 'B.Tech / Computer Science, IIT Bombay',
      experience: 'Final Year Engineering Student',
      github: 'https://github.com/rohan-sharma-tech',
      linkedin: 'https://linkedin.com/in/rohan-sharma-tech',
      portfolio: 'https://projectxia.io',
      isVerified: true,
      verificationLevel: 'Tier 1 - KYC Verified',
      isBanned: false,
      reputationScore: 96,
      savedProjects: ['proj_001_retina_ai', 'proj_002_smartagri_lora'],
      purchasedProjects: [],
    },
    {
      _id: 'user_002_creator',
      name: 'Dr. Priya Venkatesh',
      email: 'priya.creator@projectxia.io',
      mobile: '+91 94451 88720',
      role: 'creator',
      avatar: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=200&auto=format&fit=crop&q=80',
      bio: 'Lead AI Researcher & Cybersecurity Architect. Author of 6 IEEE papers on Neural Network defense & Embedded Systems.',
      skills: ['PyTorch', 'TensorRT', 'Cybersecurity', 'Rust', 'ESP32', 'FreeRTOS'],
      education: 'Ph.D in AI Security / IISc Bangalore',
      experience: 'Senior Research Scientist & Engineering Faculty',
      github: 'https://github.com/priya-venkat-ai',
      linkedin: 'https://linkedin.com/in/dr-priya-venkatesh',
      portfolio: 'https://priyavenkat.tech',
      isVerified: true,
      verificationLevel: 'Tier 3 - Master Architect',
      isBanned: false,
      reputationScore: 99,
      savedProjects: [],
      purchasedProjects: [],
    },
  ],

  agencyLeads: [
    {
      _id: 'lead_001',
      name: 'Vikas Deshmukh',
      email: 'vikas.deshmukh@vit.ac.in',
      mobile: '+91 98450 11234',
      dept: 'Electronics & Comm (ECE)',
      projectType: 'IoT / Embedded Hardware + Software',
      budget: '₹12,000 - ₹20,000',
      description: 'Need a customized Smart Water Distribution Network with LoRa 868MHz and ultrasonic level sensors for our municipal capstone submission.',
      emailCopyStatus: 'DISPATCHED_TO_THEPROJECTXIA@GMAIL.COM',
      dispatchedAt: new Date(Date.now() - 1000 * 60 * 45),
      createdAt: new Date(Date.now() - 1000 * 60 * 45),
      status: 'PENDING_REVIEW',
    },
    {
      _id: 'lead_002',
      name: 'Ananya Roy',
      email: 'ananya.roy@startuplabs.in',
      mobile: '+91 97112 33456',
      dept: 'Computer Science (CSE / IT)',
      projectType: 'Full-Stack Web / Mobile App',
      budget: '₹25,000 - ₹50,000',
      description: 'Looking to build an autonomous multi-tenant telemedicine and appointment booking portal with WebRTC video calling.',
      emailCopyStatus: 'DISPATCHED_TO_THEPROJECTXIA@GMAIL.COM',
      dispatchedAt: new Date(Date.now() - 1000 * 60 * 120),
      createdAt: new Date(Date.now() - 1000 * 60 * 120),
      status: 'QUOTE_SENT',
    },
  ],

  projects: [],

  conversations: [
    {
      _id: 'conv_001',
      participants: [
        {
          userId: 'user_001_buyer',
          name: 'Rohan Sharma',
          avatar: 'https://images.unsplash.com/photo-1535713875002-d1d0cf377fde?w=150&auto=format&fit=crop&q=80',
          role: 'user',
          isOnline: true,
          lastSeen: new Date(),
        },
        {
          userId: 'user_002_creator',
          name: 'Dr. Priya Venkatesh',
          avatar: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=150&auto=format&fit=crop&q=80',
          role: 'creator',
          isOnline: true,
          lastSeen: new Date(),
        },
      ],
      projectContext: {
        projectId: 'proj_001_retina_ai',
        title: 'DiabeticRetina-AI: Deep CNN for Retinopathy Detection',
        price: 3499,
      },
      lastMessage: {
        text: 'Hello Dr. Priya, does the PyTorch model include pre-trained weights for the Kaggle EyePACS dataset?',
        senderId: 'user_001_buyer',
        createdAt: new Date(Date.now() - 1000 * 60 * 12),
        readBy: ['user_001_buyer', 'user_002_creator'],
      },
      unreadCount: { user_001_buyer: 0, user_002_creator: 0 },
    },
  ],

  messages: [
    {
      _id: 'msg_001',
      conversationId: 'conv_001',
      sender: {
        id: 'user_001_buyer',
        name: 'Rohan Sharma',
        avatar: 'https://images.unsplash.com/photo-1535713875002-d1d0cf377fde?w=150&auto=format&fit=crop&q=80',
      },
      receiverId: 'user_002_creator',
      text: 'Hello Dr. Priya, does the PyTorch model include pre-trained weights for the Kaggle EyePACS dataset?',
      messageType: 'text',
      isRead: true,
      createdAt: new Date(Date.now() - 1000 * 60 * 25),
    },
    {
      _id: 'msg_002',
      conversationId: 'conv_001',
      sender: {
        id: 'user_002_creator',
        name: 'Dr. Priya Venkatesh',
        avatar: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=150&auto=format&fit=crop&q=80',
      },
      receiverId: 'user_001_buyer',
      text: 'Yes Rohan! Both ResNet-50 and EfficientNet-B4 weights are included in the /models directory with Grad-CAM heatmaps ready to run out of the box.',
      messageType: 'text',
      isRead: true,
      createdAt: new Date(Date.now() - 1000 * 60 * 15),
    },
  ],

  notifications: [
    {
      _id: 'notif_001',
      userId: 'user_001_buyer',
      title: 'Shield Security Verification Passed',
      message: 'Your identity was authenticated with 100% genuine clearance.',
      type: 'security_shield',
      actionUrl: '/profile',
      isRead: false,
      createdAt: new Date(Date.now() - 1000 * 60 * 30),
    },
  ],

  auditLogs: [
    {
      _id: 'log_001',
      action: 'USER_LOGGED_IN',
      category: 'AUTH_AUDIT',
      performedBy: {
        id: 'user_001_buyer',
        name: 'Rohan Sharma',
        email: 'rohan.buyer@projectxia.io',
        role: 'user',
      },
      targetEntity: {
        entityType: 'SESSION',
        entityId: 'sess_99182',
        title: 'User Login Authentication',
      },
      ipAddress: '122.164.82.11 (Airtel Broadband, Mumbai)',
      threatLevel: 'CLEAN',
      details: {
        device: 'Chrome / Windows 11 (Secure Node)',
        dispatchedEmail: 'theprojectxia@gmail.com',
        timestamp: new Date(Date.now() - 1000 * 60 * 8),
      },
      createdAt: new Date(Date.now() - 1000 * 60 * 8),
    },
    {
      _id: 'log_002',
      action: 'AGENCY_DEV_REQUEST_SUBMITTED',
      category: 'AGENCY_PIPELINE',
      performedBy: {
        id: 'lead_001',
        name: 'Vikas Deshmukh',
        email: 'vikas.deshmukh@vit.ac.in',
        role: 'client',
      },
      targetEntity: {
        entityType: 'AGENCY_LEAD',
        entityId: 'lead_001',
        title: 'IoT / LoRa Smart Water Project',
      },
      ipAddress: '115.112.45.90 (Pune, Maharashtra)',
      threatLevel: 'INFO',
      details: {
        budget: '₹12,000 - ₹20,000',
        dispatchedTo: 'theprojectxia@gmail.com',
        timestamp: new Date(Date.now() - 1000 * 60 * 45),
      },
      createdAt: new Date(Date.now() - 1000 * 60 * 45),
    },
  ],
};
